### ISSUE TITLE
ssh server forward

### ISSUE THREAD

**Issue by iecxiv** [fasmide/remotemoe#15]
Hi, I'm trying to connect to my ssh server through remote.moe.  My server is on port 6868, so on that same server I run: ssh -R22:localhost:6868 remote.moe.  It generates an address for me and I can connect from another device but I can't access the shell of my system, I stay in the access, firsttime, etc. commands.  Any idea what I'm doing wrong? Thanks in advance!

**Comment by iecxiv** [comment]
or not working!!

**Comment by fasmide** [comment]
I'm not really sure what you mean - remotemoe should indeed let you connect to forwarded ssh tunnels, by using the ProxyJump directive or simply using the `-J` parameter to ssh

https://wiki.gentoo.org/wiki/SSH_jump_host#Dynamic_jump_host_list
