### ISSUE TITLE
Remote.moe is down.

### ISSUE THREAD

**Issue by RennyDem** [fasmide/remotemoe#19]
As of today, whenever I try to connect to remote.moe, it gives out `ssh: connect to host remote.moe port 22: Connection timed out`. Is the site down? Or is my laptop malfunctioning?

**Comment by fasmide** [comment]
Yeah, I've noticed, but unfortunately, I haven't got time to work on it until this evening :)

These days, remotemoe is getting heavily used by some stable diffusion tunneling (at least that's what I think is going on based on https://github.com/Bing-su/sd-webui-tunnels - so its seen a lot of new ssh keys and traffic). This is very nice as it finally gives me an opportunity to see where the code needs optimization - and it shows - there seems to be a memory leak going on. 

At the moment, the daemon runs for about 24 hours, then gets killed by the OOM killer and restarts - and this time, I would imagine that the OOMKiller killed remotemoe just as it was writing some data to disk - and now it's in a state where it's unable to read its database properly.

**Comment by fasmide** [comment]
I think this should be resolved for now. However, it still risks getting pulled out of memory when writing files.
