### ISSUE TITLE
Comparison with sish

### ISSUE THREAD

**Issue by stokito** [fasmide/remotemoe#22]
From the [awesome-tunneling](https://github.com/anderspitman/awesome-tunneling) list I found another one similar project https://github.com/antoniomika/sish with more stars.

It looks like serves the same purpose and also is written in Golang. Can you please help me to understand differences and  pros/cons? Maybe you guys can collaborate.

There was a demo service ssi.sh but author closed it because tired from abuses. Maybe you can deploy the instance on the remote.moe to make migration easier.

There is also SSH-J.com that also provides a free service and open source. It just uses a patched Dropbear ssh server
https://bitbucket.org/ValdikSS/dropbear-sshj/
But it can't forward HTTP/HTTPS but only SSH proxy.

**UPD** another one in Golang https://github.com/pcarrier/srv.us

Looks like there is no any others FOSS SSH services that we can at least selfhost.

**Comment by fasmide** [comment]
> It looks like serves the same purpose and also is written in Golang. Can you please help me to understand differences and pros/cons? Maybe you guys can collaborate.

I have never heard about sish but at a glance, it does seem a lot like remotemoe - and it even has more stars :)

I too would love to hear about their differences - maybe there's some inspiration to be had

> There was a demo service ssi.sh but author closed it because tired from abuses. Maybe you can deploy the instance on the remote.moe to make migration easier.

I can relate, I too get some amount of abuse complaints. 
I cannot see myself running an Sish instance on my infrastructure as it just serves the purpose of having an active instance of remotemoe to profile and debug with live users. As stated in the readme:

https://github.com/fasmide/remotemoe#what-its-not

**Comment by stokito** [comment]
thank you. I came to your repo from the Awesome Tunneling list and added a link to it into the Readme in #23. I hope it would be useful and users may found something better for their purposes than annoying you with feature requests.
