### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by musahi0128** [fasmide/remotemoe#26]
Hi, I am using your service and get to the point where I can add friendlier alias for my ssh jump connection.

The server I'm working on is a disposable one. I was connecting to it using alias colab1. Now the server is gone but I am unable to use that alias anymore even while using same private key to connect, with error "hostname not available" or something along those lines.

Will the alias available, maybe after some time? Can I manage the alias even after the server I was originally connecting from is gone?

Thanks!

**Comment by musahi0128** [comment]
Hi, I need to apologize. Turn out the private key is a different one. I tried all my private key, and one is getting back to where this alias is assigned to. So now I am able to remove the alias and reuse it with another connection. Thanks!

**Comment by fasmide** [comment]
No worries! Have fun :)
