### ISSUE TITLE
Connect to host remote.moe port 22: Connection refused

### ISSUE THREAD

**Issue by kumar7679** [fasmide/remotemoe#31]
/content/2yv5aar9
ssh: connect to host remote.moe port 22: Connection refused

Please fix this problems.
![Screenshot_2](https://github.com/fasmide/remotemoe/assets/165507345/cd5f6f54-b6db-48ac-9421-791453d5207a)

**Comment by fasmide** [comment]
Hello

We are closed at the moment :)

https://github.com/fasmide/remotemoe/discussions/14

**Comment by kumar7679** [comment]
When will you start again? I will wait for this site. please tell me right answer.

**Comment by kumar7679** [comment]
> Hello
> 
> We are closed at the moment :)
> 
> #14
Please help me and please tell me right answer.
