### ISSUE TITLE
remote.moe not working

### ISSUE THREAD

**Issue by Sandy1671** [fasmide/remotemoe#33]
![remote](https://github.com/fasmide/remotemoe/assets/168395598/e9f827c7-a837-4296-91d9-06e3d4231747)
there is a problem
remote.moe (the service) is closed down until a viable authentication scheme is implemented
when it will be started again

**Comment by AstralSeeker** [comment]
yeah I was heavily using it until it suddenly closed down... I think we should move on. It's been about a week now

**Comment by fasmide** [comment]
You really shouldn't hold your breath, I'll properly not work on this until I need it back again :)
