### ISSUE TITLE
Can we use this for websockets tunnelling?

### ISSUE THREAD

**Issue by DaryeDev** [fasmide/remotemoe#8]

**Comment by fasmide** [comment]
@DaryeDev websockets in general should be no problem, is there anything particular about "websocket tunneling"?

**Comment by DaryeDev** [comment]
Exposing a local websocket server, I'm trying it with this: `ssh -R4848:localhost:4848 remote.moe`; but it can't connect on the address given (`Failed to connect to ws://---------.remote.moe:4848: [WinError 1225] El equipo remoto rechazó la conexión de red.`)

**Comment by fasmide** [comment]
You need to check your port numbers; remotemoe cannot know what to do with port 4848

I think what your looking for is something along the lines of: -R80:localhost:4848 and then connect to "ws://---------.remote.moe"

**Comment by fasmide** [comment]
bad gateway errors are not related to websockets; these appear if the ssh connection is offline or the hostname is non-existing

**Comment by DaryeDev** [comment]
Ok, everything works now. The issue was that I was using "localhost" instead of "127.0.0.1".
Thanks for your help, closing this thread.
